WebApplication_vali/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication_vali.Controllers;
using WebApplication_vali.Models;

namespace WebApplication_vali.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        WebBanVaLiEntities1 db = new WebBanVaLiEntities1();
        public ActionResult Index()
        {
            List<tDanhMucSP> LstProducts = db.tDanhMucSPs.ToList();
            return View(LstProducts);
        }
        public PartialViewResult LoaiSPPartial()
        {
            return PartialView(db.tLoaiSPs.ToList());
        }
        public ViewResult ProductByCategory(string MaLoai = "vali")
        {
            List<tDanhMucSP> LstProducts = db.tDanhMucSPs.Where(n => n.MaLoai == MaLoai).
                OrderBy(n => n.MaLoai).ToList();
            if (LstProducts.Count == 0)
            {
                ViewBag.Products = "Khong co san pham nay.";
                ViewBag.lstProducts = db.tDanhMucSPs.ToList();
            }
            return View(LstProducts);
        }
        public PartialViewResult QuocGiaSPPartial()
        {
            return PartialView(db.tQuocGias.ToList());
        }
    }
}

WebApplication_vali/Views/SanPham/Index.cshtml
@{
    ViewBag.Title = "ProductByCategory";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@using WebApplication_vali.Models;
@model List<tDanhMucSP>
@{int i = 0;
    foreach (var item in Model)
    {
        i++;
        <div class="col-lg-3 col-md-4 col-sm-6 mix vegetables fastfood">
            <div class="featured__item">
                <div class="featured__item__pic set-bg" data-setbg="@Url.Content("/image/"+item.Anh)">
                    <ul class="featured__item__pic__hover">
                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                        <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                </div>
                <div class="featured__item__text">
                    <h6><a href="#">@item.TenSP</a></h6>
                    <h5>@item.Gia</h5>
                </div>
            </div>
        </div>
        if (i % 4 == 0)
        {
            <div style="clear:both"></div>
        }
    }
}

WebApplication_vali/Views/SanPham/LoaiSPPartial.cshtml
@using WebApplication_vali.Models
@model List<tLoaiSP>

@foreach (var item in Model)
{
    <li><a href="@Url.Action("ProductByCategory", "SanPham", new {@MaLoai=item.MaLoai})">@item.Loai</a></li>
}

WebApplication_vali/Views/SanPham/ProductByCategory.cshtml
@{
    ViewBag.Title = "ProductByCategory";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
@using WebApplication_vali.Models;
@model List<tDanhMucSP>
@{int i = 0;
    foreach (var item in Model)
    {
        i++;
        <div class="col-lg-3 col-md-4 col-sm-6 mix vegetables fastfood">
            <div class="featured__item">
                <div class="featured__item__pic set-bg" data-setbg="@Url.Content("/image/"+item.Anh)">
                    <ul class="featured__item__pic__hover">
                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                        <li><a href="#"><i class="fa fa-retweet"></i></a></li>
                        <li><a href="#"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                </div>
                <div class="featured__item__text">
                    <h6><a href="#">@item.TenSP</a></h6>
                    <h5>@item.Gia</h5>
                </div>
            </div>
        </div>
        if(i%4 == 0)
                {
                    <div style="clear:both"></div>
                }
    }
}

WebApplication_vali/Views/SanPham/QuocGiaSPPartial.cshtml
@using WebApplication_vali.Models
@model List<tQuocGia>
@foreach (var item in Model)
{
    <li><a href="#">@item.TenNuoc</a></li>
}